### ISSUE TITLE
BASIC FUNCTIONALITIES: Checking for clusterability for a given undirected labelled social network

### ISSUE THREAD

**Issue by lcubrilo** [lcubrilo/Social-Nets-project#11]
- [x] #1 "Remove negative" and get components
   - [x] #4 Bug - components need all edges, not just positive
- [x] #2 Check which components are just positive and which have some negative edges
- [x] #3 Report which specific edges create issues
   - [ ] #5 Perhaps not just negative, but also positive edges are to be considered as problematic
- [x] #6 Graph of clusters
- [ ] #12
